name: uni_links_fde
description: Flutter plugin for accepting incoming links - App/Deep Links (Android), Universal Links and Custom URL schemes (iOS).
version: 0.1.4
author: Evo Stamatov <aviolito+unilinks@gmail.com>
homepage: https://github.com/avioli/uni_links

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: UniLinksPlugin

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

