name: path_provider_fde
description: Flutter plugin for getting commonly used locations on the Android &
  iOS file systems, such as the temp and app data directories.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/path_provider
version: 0.5.0+1

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: PathProviderPlugin

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter